---
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            /var/tmp/helloworld.tar:
              source: "https://s3-us-west-2.amazonaws.com/artifactory-docker/helloworld.tar"
              mode: "000777"
              
          commands:
            step1:
              command: "sudo amazon-linux-extras install docker -y"
            step2:
              command: "sudo systemctl start docker"
            step3:
              command: "sudo cat /var/tmp/helloworld.tar | sudo docker import - hello_world/app ; sleep 20"
            step4:
              command: "sudo docker run -itd -p 8080:8080 hello_world/app python /app/api/api.py"
    Properties:
      ImageId: "ami-01bbe152bf19d0289"
      InstanceType: t2.micro
      KeyName: "raghu_jenkins"
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -ex
          /opt/aws/bin/cfn-init -s ${AWS::StackName} -r EC2Instance --region ${AWS::Region}
Outputs:
  WebsiteURL:
    Description: The URL pointing the webserver
    Value: !Sub http://${EC2Instance.PublicIp}:8080