---
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            /helloworld.tar:
              source: "https://s3-us-west-2.amazonaws.com/artifactory-docker/helloworld.tar"
              mode: "000777"
              owner: "root"
              group: "root"
          commands:
            Install:
              command: "sudo amazon-linux-extras install docker -y"
            Start:
              command: "sudo systemctl start docker"
    Properties:
      ImageId: "ami-01bbe152bf19d0289"
      InstanceType: t2.micro
      KeyName: "raghu_jenkins"
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -ex
          /opt/aws/bin/cfn-init -s ${AWS::StackName} -r EC2Instance --region ${AWS::Region}
Outputs:
  WebsiteURL:
    Description: The URL pointing the webserver
    Value: !Sub http://${EC2Instance.PublicIp}