Resources:
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-01bbe152bf19d0289"
      InstanceType: "t2.small"
      KeyName: raghu_jenkins
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum update -y
            amazon-linux-extras install docker -y
            systemctl start docker
            systemctl enable docker
            wget https://github.com/raghualapati/httpserver/raw/master/Dockerfile
            sudo docker build -t raghu/app .
            sudo docker run -itd -p 8080:8080 raghu/app
Outputs:
  EC2:
    value: